### ISSUE TITLE
pip install pyphrasy -  No such file or directory: '/tmp/pip_build_root/pyphrasy/README.md'

### ISSUE THREAD

**Issue by ghost** [summerisgone/pyphrasy#8]
Доброго времени суток! 

не получается установить через pip:

Downloading/unpacking pyphrasy
  Downloading pyphrasy-0.1.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pyphrasy/setup.py) egg_info for package pyphrasy
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/pyphrasy/setup.py", line 13, in <module>
        encoding='utf') as f:
    IOError: [Errno 2] No such file or directory: '/tmp/pip_build_root/pyphrasy/README.md'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/pyphrasy/setup.py", line 13, in <module>

```
encoding='utf') as f:
```

IOError: [Errno 2] No such file or directory: '/tmp/pip_build_root/pyphrasy/README.md'

---

Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/pyphrasy
Storing debug log for failure in /home/ubuntu/.pip/pip.log

**Comment by ojomio** [comment]
But I cannot check it because I have no access to pypi registration for this repo

**Comment by alloky** [comment]
Обнаружил (через отладчик pycharm) что так происходит из-за того что файл README.md не загружается из pypi при установке. Проверьте пожалуйста, залит ли он в репу. Возможно он игнорится какой-то настройкой pypi или pip

**Comment by alloky** [comment]
#13 должен решить эту проблему судя по https://stackoverflow.com/questions/34415182/pypi-pip-installed-package-receive-error-reading-readme-md

**Comment by summerisgone** [comment]
Спасибо! Обновлю немного проект заодно
